<?php


namespace App\Libs\CoolHSDK;


use App\Libs\CoolHSDK\Facades\Facade;
use App\Libs\CoolHSDK\SDK\assetSdk;
use App\Libs\CoolHSDK\SDK\directMessageSdk;
use App\Libs\CoolHSDK\SDK\guildRoleSdk;
use App\Libs\CoolHSDK\SDK\guildSdk;
use App\Libs\CoolHSDK\SDK\inviteSdk;
use App\Libs\CoolHSDK\SDK\messageSdk;
use App\Libs\CoolHSDK\SDK\userSdk;

class Coolh extends Facade
{
    public static function getUser(?string $token = null): userSdk
    {
        return new userSdk($token); // TODO: Change the autogenerated stub
    }

    public static function getMessage(?string $token = null): messageSdk
    {
        return new messageSdk($token); // TODO: Change the autogenerated stub
    }

    public static function getDirectMessage(?string $token = null): directMessageSdk
    {
        return new directMessageSdk($token); // TODO: Change the autogenerated stub
    }

    public static function getGuildRole(?string $token = null): guildRoleSdk
    {
        return new guildRoleSdk($token); // TODO: Change the autogenerated stub
    }

    public static function getGuild(?string $token = null): guildSdk
    {
        return new guildSdk($token); // TODO: Change the autogenerated stub
    }

    public static function getInvite(?string $token = null): inviteSdk
    {
        return new inviteSdk($token); // TODO: Change the autogenerated stub
    }

    public static function getAsset(?string $token = null): assetSdk
    {
        return new assetSdk($token); // TODO: Change the autogenerated stub
    }
}
